apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
  namespace: myapp-dev
  labels:
    app: games
    environment: ${ENVIRONMENT}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: games
          image: ${IMAGE_TAG}
          env:
            # Основные переменные
            - name: NODE_ENV
              value: ${ENVIRONMENT}
            - name: SERVICE_NAME
              value: games

            - name: POSTGRES_PASSWORD
              value: '0896'
            - name: POSTGRES_HOST
              value: 'postgres'

          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
