apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: myapp-dev
  labels:
    app: users
    environment: ${ENVIRONMENT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: users
          image: ${IMAGE_TAG}
          env:
            # Основные переменные
            - name: NODE_ENV
              value: ${ENVIRONMENT}
            - name: SERVICE_NAME
              value: users

            - name: POSTGRES_PASSWORD
              value: '0896'
            - name: POSTGRES_HOST
              value: 'postgres'

          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
