apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
    environment: ${ENVIRONMENT}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${IMAGE_TAG}
          env:
            # Основные переменные
            - name: NODE_ENV
              value: ${ENVIRONMENT}
            - name: SERVICE_NAME
              value: ${SERVICE_NAME}

            - name: POSTGRES_PASSWORD
              value: '${POSTGRES_PASSWORD}'
            - name: POSTGRES_HOST
              value: '${POSTGRES_HOST}'

          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
